var re4 = document.getElementById("adolf-san")

re4.innerHTML = "Since 5:45 am we have been returning fire. And from now on, bombs will be met with bombs. Whoever fights with poison gas will be fought with poison gas. Whoever departs from the rules of humane warfare can only expect us to do the same. I will continue this struggle, no matter against whom, until the security of the Reich and its rights are secured  ~ by hitler"
 var re5 = document.getElementsByClassName('adolf-chan')

 re5[0].style.backgroundColor = "cyan"
 re5[1].style.backgroundColor = "purple"
 re5[1].style.width = "460px"

