// OBJECT COULD BE ANY THING 

function uss(a,b){
    return a*b
}

var a = uss(a,b)
console.log(a)

var b = {age: 25, johncena: function(v,m){return v*m}
}

var c = b.johncena(6,7)
console.log(c)

console.log(Math.random())
console.log(Math.floor(7.6))
console.log(Math.ceil(7.4))

var tacos = 'walid eats food'
console.log(tacos.toUpperCase())

var i 
for(i=0; i<30; i++){
    console.log("I LOVE TO EAT MANCHRIANS")
    console.log("NOODLES INCLUDED")
}

